#!/usr/bin/env python3
# =============================================================================
#   SDDM Screen Selection & Display Properties Manager
#   Part of: CachyOS + HyDE System Restorer
#   Repo:    https://github.com/omarahmed321/cachyos-restore
# =============================================================================

import os
import sys
import re
import subprocess
import tkinter as tk
from tkinter import ttk, messagebox

SDDM_CONF_DIR = "/etc/sddm.conf.d"
SDDM_DISPLAY_CONF = "/etc/sddm.conf.d/10-display.conf"

def get_monitors_info():
    monitors = {}
    try:
        output = subprocess.check_output(['hyprctl', 'monitors'], text=True)
        chunks = output.split('Monitor ')[1:]
        for chunk in chunks:
            lines = chunk.strip().split('\n')
            if not lines:
                continue
            match_name = re.match(r'^(\S+)\s+\(ID', lines[0])
            if not match_name:
                continue
            name = match_name.group(1)
            
            info = {
                'name': name,
                'model': 'Unknown',
                'resolution': 'Unknown',
                'refresh_rate': 'Unknown',
                'scale': '1.00',
                'position': '0x0',
                'focused': False
            }
            
            if len(lines) > 1:
                match_mode = re.search(r'(\d+x\d+)@(\d+(?:\.\d+)?)\s+at\s+(\d+x\d+)', lines[1])
                if match_mode:
                    info['resolution'] = match_mode.group(1)
                    info['refresh_rate'] = f"{float(match_mode.group(2)):.2f} Hz"
                    info['position'] = match_mode.group(3)
            
            for line in lines:
                line_str = line.strip()
                if line_str.startswith('model:'):
                    info['model'] = line_str.split('model:')[1].strip()
                elif line_str.startswith('scale:'):
                    info['scale'] = line_str.split('scale:')[1].strip()
                elif 'focused: yes' in line_str:
                    info['focused'] = True
                    
            monitors[name] = info
    except Exception as e:
        print(f"Warning: hyprctl failed ({e}). Attempting xrandr fallback...")
        try:
            output = subprocess.check_output(['xrandr'], text=True)
            for line in output.splitlines():
                if ' connected' in line:
                    parts = line.split()
                    name = parts[0]
                    monitors[name] = {
                        'name': name,
                        'model': 'Connected Display',
                        'resolution': 'Default',
                        'refresh_rate': '60 Hz',
                        'scale': '1.00',
                        'position': '0x0',
                        'focused': 'primary' in line
                    }
        except Exception:
            pass
            
    return monitors

def apply_sddm_screen(target_screen):
    try:
        # Create temporary script to write config via pkexec/sudo if needed
        tmp_conf = f"/tmp/10-display.conf"
        content = f"""# Generated by SDDM Screen Manager
[X11]
DisplayCommand=/usr/share/sddm/scripts/Xsetup

[Wayland]
CompositorCommand=kwin_wayland --drm --output-order {target_screen}
"""
        with open(tmp_conf, 'w') as f:
            f.write(content)

        # Apply using sudo/pkexec
        cmd = f"sudo mkdir -p {SDDM_CONF_DIR} && sudo cp {tmp_conf} {SDDM_DISPLAY_CONF} && sudo chmod 644 {SDDM_DISPLAY_CONF}"
        res = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        if res.returncode != 0:
            # Fallback using pkexec
            subprocess.run(f"pkexec bash -c '{cmd}'", shell=True, check=True)
        
        return True
    except Exception as e:
        messagebox.showerror("Error", f"Failed to update SDDM config: {e}")
        return False

class SDDMScreenApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("SDDM Display & Screen Selector")
        self.geometry("540x480")
        self.configure(bg='#272727')
        
        self.monitors = get_monitors_info()
        self.selected_screen = tk.StringVar()
        
        if self.monitors:
            default_screen = list(self.monitors.keys())[0]
            for m, data in self.monitors.items():
                if data['focused']:
                    default_screen = m
                    break
            self.selected_screen.set(default_screen)
            
        self.setup_styles()
        self.build_ui()
        
    def setup_styles(self):
        style = ttk.Style()
        style.theme_use('clam')
        style.configure('.', background='#272727', foreground='#ebdbb2', font=('JetBrains Mono', 10))
        style.configure('TLabel', background='#272727', foreground='#ebdbb2')
        style.configure('TLabelframe', background='#272727', foreground='#fabd2f')
        style.configure('TLabelframe.Label', background='#272727', foreground='#fabd2f', font=('JetBrains Mono', 10, 'bold'))
        style.configure('TRadiobutton', background='#3c3836', foreground='#ebdbb2', font=('JetBrains Mono', 10))
        style.configure('TButton', background='#3c3836', foreground='#ebdbb2', padding=[10, 5])
        style.map('TButton', background=[('active', '#504945')])

    def build_ui(self):
        header = ttk.Label(self, text="🖥️ SDDM Login Screen Selector", font=('JetBrains Mono', 13, 'bold'), foreground='#83a598')
        header.pack(pady=(15, 5))
        
        sub = ttk.Label(self, text="Select which screen SDDM should display on during boot:", font=('JetBrains Mono', 9), foreground='#a89984')
        sub.pack(pady=(0, 15))
        
        container = ttk.Frame(self)
        container.pack(fill='both', expand=True, padx=20, pady=10)
        
        if not self.monitors:
            ttk.Label(container, text="No monitors detected via hyprctl.", foreground='#fb4934').pack()
            return
            
        for name, info in self.monitors.items():
            lf = ttk.LabelFrame(container, text=f" Screen: {name} {'(Primary/Active)' if info['focused'] else ''} ")
            lf.pack(fill='x', pady=8, padx=5)
            
            rb = ttk.Radiobutton(lf, text=f"Use {name} for SDDM Login", value=name, variable=self.selected_screen)
            rb.pack(anchor='w', padx=10, pady=5)
            
            props = f"• Model: {info['model']}\n• Resolution: {info['resolution']}\n• Refresh Rate: {info['refresh_rate']}\n• Scaling: {info['scale']}x | Pos: {info['position']}"
            ttk.Label(lf, text=props, justify='left', foreground='#bdae93').pack(anchor='w', padx=25, pady=(0, 8))
            
        btn_frame = ttk.Frame(self)
        btn_frame.pack(fill='x', side='bottom', padx=20, pady=15)
        
        ttk.Button(btn_frame, text="Close", command=self.destroy).pack(side='left')
        ttk.Button(btn_frame, text="Apply SDDM Screen Config", command=self.save).pack(side='right')

    def save(self):
        target = self.selected_screen.get()
        if not target:
            messagebox.showerror("Error", "Please select a target display.")
            return
            
        if apply_sddm_screen(target):
            messagebox.showinfo("Success", f"SDDM login screen target set to {target} successfully!\nConfig written to {SDDM_DISPLAY_CONF}")

if __name__ == "__main__":
    if not os.environ.get('WAYLAND_DISPLAY') and not os.environ.get('DISPLAY'):
        print("Error: No display environment found.")
        sys.exit(1)
    app = SDDMScreenApp()
    app.mainloop()
