#!/usr/bin/env bash
if [ -z "$1" ]; then
    read -p "Enter new todo task: " TASK_TEXT
    if [ -n "$TASK_TEXT" ]; then
        python3 "$HOME/.local/share/bin/manage_tasks.py" todo "$TASK_TEXT"
        fastfetch
    fi
else
    python3 "$HOME/.local/share/bin/manage_tasks.py" todo "$@"
    fastfetch
fi
